-- =============================================
-- 变更说明: ficc fiadvisor.dwd_position_di definition
-- 作者:     huixue
-- 日期:     2026-07-12
-- 用途:
-- =============================================


CREATE TABLE `dwd_position_di` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint DEFAULT NULL COMMENT '是否删除标志,0未删除，1删除',
  `beg_date` date DEFAULT NULL COMMENT '估值日期',
  `asset_name` varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产名称\n',
  `asset_code` varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产代码',
  `wind_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'wind的代码',
  `asset_type` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产类型',
  `i_code` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产代码',
  `m_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '交易市场',
  `prod_id` bigint DEFAULT NULL COMMENT '产品ID',
  `secu_accid` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '账户代码',
  `pos_amt` decimal(38,6) DEFAULT NULL COMMENT '持仓数量',
  `post_cost_ful` decimal(38,6) DEFAULT NULL COMMENT '持仓成本（全价）',
  `fair_pri` decimal(38,6) DEFAULT NULL COMMENT '公允价格',
  `pos_market_val_ful` decimal(38,6) DEFAULT NULL COMMENT '持仓市值（全价）',
  `float_profit_net` decimal(38,6) DEFAULT NULL COMMENT '浮动盈亏（净价）',
  `float_profit_ful` decimal(38,6) DEFAULT NULL COMMENT '浮动盈亏（全价）',
  `issuer` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发行主体',
  `guarantor` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '担保人',
  `pos_amt_div_issue_amt` decimal(38,6) DEFAULT NULL COMMENT '单券持仓量/证券发行量',
  `post_cost_div_net_amt` decimal(38,6) DEFAULT NULL COMMENT '持仓成本/产品净资产',
  `net_amt` decimal(38,6) DEFAULT NULL COMMENT '产品净资产',
  `latest_couponrate` decimal(20,4) DEFAULT NULL COMMENT '票面利率（最新）',
  `eval_ytm_ex_opt_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价YTM（中债行权）',
  `eval_mod_dur_ex_opt_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价修正久期（中债行权）\n',
  `ptmyear` decimal(20,4) DEFAULT NULL COMMENT '剩余期限',
  `province` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '省份',
  `city` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '城市',
  `comp_property` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '企业性质 ',
  `credit_rating` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '债项评级 ',
  `comp_rating` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '主体评级 ',
  `credit_rating_cnbd` varchar(300) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '中债隐含评级',
  `if_city_inv` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否城投 ',
  `issue_type` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发行方式',
  `wind_industry_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '债券类型 -wind一级分类',
  `ex_opt_date` date DEFAULT NULL COMMENT '行权日 ',
  `interest_rate_credit` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '利率信用 1:利率债 3:城投债 4:产业债',
  `guarantor_rating` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '担保人评级',
  `denomination` decimal(20,4) DEFAULT NULL COMMENT '持仓面值',
  `pos_weight` decimal(20,6) DEFAULT NULL COMMENT '持仓权重',
  `total_pos_market_value_ful` decimal(38,6) DEFAULT NULL COMMENT '总持仓市值\n',
  `net_pri` decimal(38,6) DEFAULT NULL COMMENT '净价',
  `pos_market_value_net` decimal(38,6) DEFAULT NULL COMMENT '持仓市值（净价）',
  `cost_pri_net` decimal(38,6) DEFAULT NULL COMMENT '成本价格（净价）',
  `cost_pri_ful` decimal(38,6) DEFAULT NULL COMMENT '成本价格（全价）',
  `daily_profit` decimal(38,6) DEFAULT NULL COMMENT '当日盈亏',
  `daily_profit_net` decimal(38,6) DEFAULT NULL COMMENT '当日盈亏(净价)',
  `credibility_cnbd` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '可信度（中债）',
  `eval_net_ex_opt_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价净价（中债行权）',
  `eval_net_expir_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价净价（中债到期）',
  `eval_ful_ex_opt_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价全价（中债行权）',
  `eval_ful_expir_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价全价（中债到期）',
  `eval_ytm_expir_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价YTM（中债到期）',
  `eval_mod_dur_expir_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价修正久期（中债到期）',
  `eval_cvx_ex_opt_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价凸性（中债行权）',
  `eval_cvx_expir_cnbd` decimal(20,4) DEFAULT NULL COMMENT '估价凸性（中债到期）',
  `credibility_csi` tinyint DEFAULT NULL COMMENT '可信度（中证）',
  `eval_net_ex_opt_csi` decimal(20,4) DEFAULT NULL COMMENT '估价净价（中证行权）',
  `eval_net_expir_csi` decimal(20,4) DEFAULT NULL COMMENT '估价净价（中证到期）',
  `eval_ful_ex_opt_csi` decimal(20,4) DEFAULT NULL COMMENT '估价全价（中证行权）',
  `eval_ful_expir_csi` decimal(20,4) DEFAULT NULL COMMENT '估价全价（中证到期）',
  `eval_ytm_ex_opt_csi` decimal(20,4) DEFAULT NULL COMMENT '估价YTM（中证行权）',
  `eval_ytm_expir_csi` decimal(20,4) DEFAULT NULL COMMENT '估价YTM（中证到期）',
  `eval_mod_dur_ex_opt_csi` decimal(20,4) DEFAULT NULL COMMENT '估价修正久期（中证行权）',
  `eval_mod_dur_expir_csi` decimal(20,4) DEFAULT NULL COMMENT '估价修正久期（中证到期）',
  `eval_cvx_ex_opt_csi` decimal(20,4) DEFAULT NULL COMMENT '估价凸性（中证行权）',
  `eval_cvx_expir_csi` decimal(20,4) DEFAULT NULL COMMENT '估价凸性（中证到期）',
  `close_net` decimal(20,8) DEFAULT NULL COMMENT '收盘价净价',
  `close_ful` decimal(20,8) DEFAULT NULL COMMENT '收盘价全价',
  `close_ytm` decimal(24,8) DEFAULT NULL COMMENT '收盘价YTM',
  `mod_dur` decimal(24,8) DEFAULT NULL COMMENT '收盘价修正久期',
  `close_cvx` decimal(24,8) DEFAULT NULL COMMENT '收盘价凸性',
  `cost_ytm` decimal(20,4) DEFAULT NULL COMMENT '成本YTM',
  `hgir` decimal(38,6) DEFAULT NULL COMMENT '应计利息',
  `pos_cost_net` decimal(38,6) DEFAULT NULL COMMENT '持仓成本（净价）',
  `close_dv01` decimal(38,6) DEFAULT NULL COMMENT '收盘价DV01',
  `wind_industry_name2` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '债券类型 -wind二级分类',
  `administrative_level` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '行政级别 ',
  `if_sustainable` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否永续 ',
  `next_payment_date` date DEFAULT NULL COMMENT '下一付息日',
  `maturity_date` date DEFAULT NULL COMMENT '到期日 ',
  `after_tx_roi` decimal(38,6) DEFAULT NULL COMMENT '税返买入收益率 ',
  `sw_risk_ctr_rating` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '公司风控评级 ',
  `sw_pool_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '证券池',
  `remark` text COLLATE utf8mb4_general_ci COMMENT '备注',
  `daily_int_inc` decimal(20,6) DEFAULT NULL COMMENT '当日利息收入',
  `daily_int_inc_realized` decimal(20,6) DEFAULT NULL COMMENT '当日利息收入(已实现)',
  `daily_int_inc_unrealized` decimal(20,6) DEFAULT NULL COMMENT '当日利息收入(未实现)',
  `daily_cap_gain` decimal(20,6) DEFAULT NULL COMMENT '当日资本利得',
  `daily_cap_gain_realized` decimal(20,6) DEFAULT NULL COMMENT '当日资本利得(已实现)',
  `daily_cap_gain_unrealized` decimal(20,6) DEFAULT NULL COMMENT '当日资本利得(未实现)',
  `bond_type1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '债券一级板块名称',
  `bond_type2` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '债券二级板块名称',
  `rpch_start_date` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '回售行使开始日',
  `rpch_end_date` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '回售行使截止日',
  `daily_pnl` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_clearance_bond` tinyint DEFAULT '0' COMMENT '是否清仓债 1：是 0 ：否',
  `b_anal_accrint_csi` decimal(20,4) DEFAULT NULL COMMENT '应计利息（中证推荐）',
  `b_anal_accrint_cnbd` decimal(20,4) DEFAULT NULL COMMENT '应计利息（中债推荐）',
  `eval_category` tinyint DEFAULT '0' COMMENT '估值类别,0-原始估值,2-第二估值',
  `sw_rating_rel_subj` varchar(40) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '风控内评（关联主体）',
  `term_if_exercise` decimal(22,4) DEFAULT NULL COMMENT '行权剩余期限',
  `term_note` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '剩余期限说明',
  `hold_face_amount` decimal(38,6) DEFAULT NULL COMMENT '持仓面额=持仓数量*持仓面值',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_begdt` (`beg_date`) USING BTREE,
  KEY `idx_accid_begdt` (`secu_accid`,`beg_date`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10081159 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='持仓全景';

