-- =============================================
-- 变更说明: ficc fiadvisor prod_base_info definition
-- 作者:     huixue
-- 日期:     2026-05-26
-- 用途:
-- =============================================
--

CREATE TABLE `prod_base_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id，主键',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建者',
  `update_by` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新者',
  `is_deleted` tinyint DEFAULT '0' COMMENT '是否删除标志,0未删除，1删除',
  `data_src` tinyint unsigned DEFAULT NULL COMMENT '数据源',
  `prod_id` bigint unsigned DEFAULT NULL COMMENT '产品ID',
  `prod_creator` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '产品创建人',
  `prod_name` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '产品名称 AMS支持最多40个字符',
  `prod_start_date` date DEFAULT NULL COMMENT '产品起始日',
  `actual_prod_start_date` date DEFAULT NULL COMMENT '实际服务起始日',
  `actual_prod_start_date_source` tinyint DEFAULT '0' COMMENT '1:系统修改 0 ：页面修改',
  `prod_end_date` date DEFAULT NULL COMMENT '产品到期日',
  `trans_start_dt` date DEFAULT NULL COMMENT '交易起始日',
  `prod_base_curr` tinyint unsigned DEFAULT NULL COMMENT '产品本币',
  `inv_nature` tinyint unsigned DEFAULT NULL COMMENT '投资性质',
  `raise_method` tinyint unsigned DEFAULT NULL COMMENT '募集方式',
  `exist_duration` tinyint unsigned DEFAULT NULL COMMENT '存续期限',
  `perf_bm` varchar(50) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '业绩基准',
  `rtn_algo` tinyint unsigned DEFAULT NULL COMMENT '回报算法',
  `prod_cal` tinyint unsigned DEFAULT NULL COMMENT '产品日历',
  `prod_share` decimal(20,6) unsigned DEFAULT NULL COMMENT '产品份额',
  `prod_share_input_method` tinyint DEFAULT NULL COMMENT '产品份额录入方式',
  `manager` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '管理人',
  `inv_manager` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '投资经理',
  `status` tinyint unsigned DEFAULT '0' COMMENT '产品状态 1-正常 2-终止',
  `acc_code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '账户代码 衡泰内证账户代码',
  `cp_bank_acc` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '对手方银行账号 衡泰入金流水的银行账号',
  `principal` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '委托人/资金方',
  `custodian` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '托管人',
  `init_mand_size` varchar(100) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '初始委托规模',
  `is_spec_cust_prod` tinyint DEFAULT '0' COMMENT '是否特殊定制产品,1-是 0-否',
  `open_branch_name` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '开户营业部',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `bid_cost` decimal(20,6) DEFAULT '0.000000' COMMENT '投标及相关费用',
  `bid_cost_cmt` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '投标及相关费用说明',
  `has_benefit_period` tinyint unsigned DEFAULT '0' COMMENT '是否存在受益权期数,0-否,1-是',
  `is_sign_memo` tinyint unsigned DEFAULT '0' COMMENT '是否已签备忘录,0-否,1-是',
  `category` tinyint DEFAULT NULL COMMENT '分类',
  `form` tinyint DEFAULT NULL COMMENT '形式',
  `manage_fee` decimal(10,6) DEFAULT NULL COMMENT '托管费（%）',
  `custody_fee` decimal(10,6) DEFAULT NULL COMMENT '托管费（%）',
  `agen_sale_fee` decimal(10,6) DEFAULT NULL COMMENT '代销费（%）',
  `is_occupy_cap` tinyint DEFAULT NULL COMMENT '是否占资法',
  `principal_id` bigint DEFAULT NULL COMMENT '委托人/资金方ID',
  `custodian_id` bigint DEFAULT NULL COMMENT '托管人ID',
  `prod_type` int DEFAULT NULL COMMENT '产品类型：1：真实 2：虚拟',
  `incld_head_tail` tinyint DEFAULT '0' COMMENT '产品运行天数头尾计算规则，字典，含头不含尾0，含头含尾1。默认0 ',
  `fixed_advis_fee` decimal(10,6) DEFAULT NULL COMMENT '固定投顾费（%）',
  `excs_cust_provis_ratio` decimal(10,6) DEFAULT NULL COMMENT '超额客户计提比例',
  `is_sync_eval` tinyint DEFAULT '0' COMMENT '是否需要同步估值单数据',
  `strategy` tinyint DEFAULT NULL COMMENT '策略，1：利率 ，2：信用  3：信用+利率',
  `is_has_stock` tinyint DEFAULT NULL COMMENT '是否包含股票:0否1是',
  `is_has_public_fund` tinyint DEFAULT NULL COMMENT '是否包含公募基金:0否1是',
  `is_has_private_asset` tinyint DEFAULT NULL COMMENT '是否包含私募资管:0否1是',
  `is_has_private_fund` tinyint DEFAULT NULL COMMENT '是否包含私募基金:0否1是',
  `is_has_exchange_bond` tinyint DEFAULT NULL COMMENT '是否包含交易所债券、债券回购:0否1是',
  `is_has_exchange_depository` tinyint DEFAULT NULL COMMENT '是否包含交易所存托凭证、资产支持证券:0否1是',
  `is_has_interbank_bond` tinyint DEFAULT NULL COMMENT '是否包含银行间债券市场产品:0否1是',
  `is_has_financial_futures` tinyint DEFAULT NULL COMMENT '是否包含金融期货合约:0否1是',
  `is_has_commodity_futures` tinyint DEFAULT NULL COMMENT '是否包含商品期货合约:0否1是',
  `is_has_option` tinyint DEFAULT NULL COMMENT '是否包含期权:0否1是',
  `is_has_forex_derivatives` tinyint DEFAULT NULL COMMENT '是否包含外汇衍生品:0否1是',
  `is_has_other` tinyint DEFAULT NULL COMMENT '是否包含其他:0否1是',
  `is_amortized_cost` tinyint DEFAULT NULL COMMENT '是否摊余成本法0否1是',
  `prod_name_fix` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修正产品名称',
  `leverage_limit` decimal(20,6) DEFAULT NULL COMMENT '杠杆上限',
  `duration_limit` decimal(20,6) DEFAULT NULL COMMENT '久期上限',
  PRIMARY KEY (`id`),
  KEY `idx_prodid` (`prod_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=100155 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='产品基本信息';